### ISSUE TITLE
Crash when video finished on Android

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/videoPlayer-ANE#20]
When I play the same video file second time, during app session, app crashes when complete.
Flash log:
```
[Fault] exception, information=Error: EncryptedLocalStore is out of memory
at flash.data::EncryptedLocalStore$/processErrorCode()
at flash.data::EncryptedLocalStore$/getItem()
at com.myflashlab.air.extensions.gameServices.google::ApiBase/getEncryptedLocalStore()
at com.myflashlab.air.extensions.gameServices.google.auth::Android/handleDeactivate()
at com.myflashlab.air.extensions.gameServices.google.auth::Android/onStatus()
at com.myflashlab.air.extensions.gameServices.google::GoogleApi/onStatus()

```

Android log:
```
12-14 17:40:37.432	16411	16411	W	System.err	java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.ContextWrapper.getApplicationContext()' on a null object reference
12-14 17:40:37.443	16411	16411	W	System.err		at com.adobe.air.AndroidEncryptedLocalStore.getItem(AndroidEncryptedLocalStore.java:48)
12-14 17:40:37.443	16411	16411	W	System.err		at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
12-14 17:40:37.443	16411	16411	W	System.err		at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
12-14 17:40:37.443	16411	16411	W	System.err		at android.os.Handler.dispatchMessage(Handler.java:102)
12-14 17:40:37.443	16411	16411	W	System.err		at android.os.Looper.loop(Looper.java:154)
12-14 17:40:37.443	16411	16411	W	System.err		at android.app.ActivityThread.main(ActivityThread.java:6682)
12-14 17:40:37.443	16411	16411	W	System.err		at java.lang.reflect.Method.invoke(Native Method)
12-14 17:40:37.443	16411	16411	W	System.err		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
12-14 17:40:37.443	16411	16411	W	System.err		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

AS3 code:
```
                public function playFile(url:String, volume:Number = 1):void
		{
			if (permissionCheckerModel.storagePermissionGranted)
			{
				// copy test video to sdcard
				var src:File = File.applicationDirectory.resolvePath(url);
				var dis:File = File.documentsDirectory.resolvePath("exVideoPlayer.mp4");
				try
				{
					src.copyTo(dis, true);
					player.play(dis.nativePath, VideoType.ON_SD_CARD);
				} catch (e:Error)
				{
					dispatchMessage(VideoPlayerMessage.ON_COMPLETE, null, true);
				}
			} else
			{
				playVideoType = VideoType.ON_SD_CARD;
				playVideoURL = url;

				permissionCheckerModel.checkStorage();
			}
		}
```

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
